"""Declarative base and the two stamps every table carries.

⚠️ `DateTime(timezone=True)`, FROM THE FIRST TABLE, and that is a lesson bought elsewhere.
Le Comptoir Immo grew a naive `timestamp` on fifty-one tables and an aware one on
seventeen — nobody chose it, it accreted — and on 17 August 2026 the two schemas had to be
compared column by column to find out which was which. A new product has no excuse: a stamp
is an INSTANT, and an instant without its zone is a wall clock that means something
different in Abidjan and in Paris.

The fund is multi-currency and will have investors in several zones. There is no version of
this product where a naive timestamp is correct.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


def uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key, generated by the application.

    Not a sequence: an investor identifier appears in URLs, in e-mails and in documents
    sent outside, and a sequential one tells the reader how many investors the fund has.
    """
    return mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """When the row was written, and when it was last touched. Both AWARE."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
