"""Accounts: who signs in, and as what.

⚠️ AN ACCOUNT IS NOT AN INVESTOR. The record and the way in are two objects, and this is
the pattern the sister product already runs for its tenants and its landlords
(`Tenant.user_id`, `Owner.user_id`). The reasons it matters here:

  * an investor may exist with NO account — a paper subscriber, an estate, a company whose
    signatory has not been given access yet. Their money, their units and their statements
    all exist regardless;
  * an account may be closed, disabled or handed to another person without the investor's
    holdings moving an inch;
  * and the same human may be an investor here and a landlord in Le Comptoir Immo. The
    holdings belong to the investor record; the login belongs to the person.

Folding the two into one row makes « disable this login » and « this investor no longer
holds anything » the same operation, and they are never the same operation.

WHERE MANAGER ACCOUNTS COME FROM. Not from here: the house rule is that everything about a
MANAGER — creation, plan, entitlements — belongs to Alice, and each product refuses to mint
one. Investor accounts are the opposite: they are created inside the product by the manager,
exactly as a tenant's is in Le Comptoir Immo.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, uuid_pk

#: Runs the fund. Created by Alice, never by this product.
MANAGER = "manager"
#: Sees their own portfolio and nothing else. Created here, by the manager.
INVESTOR = "investor"
#: Platform administration.
ADMIN = "admin"

ROLES: tuple[str, ...] = (ADMIN, MANAGER, INVESTOR)

#: Roles that may see the fund as a whole. Everything an investor is shown is scoped to
#: their own record, and that scoping is a rule of the API, not a habit of the screens: a
#: portal that filters in the front end has already sent the data.
FUND_WIDE_ROLES: tuple[str, ...] = (ADMIN, MANAGER)


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = uuid_pk()
    email: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True, index=True
    )
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    #: What is printed and greeted. Distinct from the investor's legal name: a signatory
    #: acting for a company signs in under their own.
    account_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    role: Mapped[str] = mapped_column(String(20), nullable=False, index=True)

    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="true"
    )
    #: A provisioned account whose password was handed over and must be replaced at first
    #: sign-in. A credential someone else has seen is not the holder's.
    must_change_password: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    last_login_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    #: Interface language, stored so a statement generated by a scheduled job — with no
    #: request and therefore no `Accept-Language` — still reaches the investor in theirs.
    #: The sister product had to add this column after the fact for exactly that reason.
    locale: Mapped[str] = mapped_column(
        String(5), nullable=False, default="fr", server_default="fr"
    )

    # ── Postal identity, pushed by Alice ──────────────────────────────────────────────
    #: 🔴 THESE COLUMNS EXIST BECAUSE ALICE SENDS THEM. A schema that does not name a
    #: field drops it silently: the console pushes an address, the product has nowhere to
    #: put it, nothing fails — and months later the invoice goes out with an empty
    #: addressee. They serve billing only, never the application itself.
    phone: Mapped[str | None] = mapped_column(String(30), nullable=True)
    address: Mapped[str | None] = mapped_column(Text, nullable=True)
    zip_code: Mapped[str | None] = mapped_column(String(20), nullable=True)
    city: Mapped[str | None] = mapped_column(String(120), nullable=True)
    country: Mapped[str | None] = mapped_column(String(80), nullable=True)
    #: 🔴 LE NUMERO DE LA SOCIETE DE GESTION, pas celui d'un bailleur. Alice pousse aussi
    #: une identite de bailleur (`owner_national_id`) que ce produit recoit et NE GARDE PAS,
    #: parce qu'un fonds n'en a pas. Celui-ci est l'identite de l'entite qui souscrit au
    #: logiciel et figure sur ses factures.
    #:
    #: ⚠️ NULL EST LEGITIME : les comptes anterieurs n'en ont pas, et une societe hors de
    #: France porte un numero d'une autre forme. Un NOT NULL aurait empeche la console de
    #: creer un compte qu'elle sait creer aujourd'hui.
    national_id: Mapped[str | None] = mapped_column(String(40), nullable=True)

    @property
    def sees_whole_fund(self) -> bool:
        """One place answers it, so no endpoint decides on its own."""
        return self.role in FUND_WIDE_ROLES

    def __repr__(self) -> str:
        return f"<User {self.email} [{self.role}]>"
