"""Baseline: investisseurs, souscriptions, tresorerie

The whole schema in one revision, because there is no history to preserve: this product
has never had a database. Every later change is a revision of its own.

⚠️ `alembic upgrade head` against an EMPTY schema is what a new deployment does, and the
`-x schema=` mechanism in `env.py` is what proves it still works. The sister product had
that mechanism and never ran it: its chain had been unable to reach head for fifty-two
revisions, and nothing said so until somebody tried. A guard exercises it here from the
first day.

Revision ID: a1f6c72ace9f
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_iban", sa.String(length=34), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("counterparty_name", sa.String(length=255), nullable=True),
        sa.Column("counterparty_iban", sa.String(length=34), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bank_movements_account_iban"),
        "bank_movements",
        ["account_iban"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_movements_currency"), "bank_movements", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_bank_movements_value_date"),
        "bank_movements",
        ["value_date"],
        unique=False,
    )
    op.create_index(
        "uq_bank_movement_external",
        "bank_movements",
        ["account_iban", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locale", sa.String(length=5), server_default="fr", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "investors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("national_id", sa.String(length=60), nullable=True),
        sa.Column("born_on", sa.Date(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("zip_code", sa.String(length=20), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("iban_encrypted", sa.Text(), nullable=True),
        sa.Column("iban_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("bic", sa.String(length=11), nullable=True),
        sa.Column("virtual_iban", sa.String(length=34), nullable=True),
        sa.Column("payout_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "kyc_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "kyc_risk_level",
            sa.String(length=20),
            server_default="standard",
            nullable=False,
        ),
        sa.Column("kyc_decided_by", sa.String(length=150), nullable=True),
        sa.Column("kyc_decided_on", sa.Date(), nullable=True),
        sa.Column("kyc_reason", sa.Text(), nullable=True),
        sa.Column("is_pep", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("source_of_funds", sa.Text(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("virtual_iban"),
    )
    op.create_index(
        op.f("ix_investors_country_code"), "investors", ["country_code"], unique=False
    )
    op.create_index(op.f("ix_investors_email"), "investors", ["email"], unique=False)
    op.create_index(
        op.f("ix_investors_iban_fingerprint"),
        "investors",
        ["iban_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investors_user_id"), "investors", ["user_id"], unique=False
    )
    op.create_table(
        "investor_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investor_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("collected_by", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["investor_id"], ["investors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investor_documents_expires_on"),
        "investor_documents",
        ["expires_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investor_documents_investor_id"),
        "investor_documents",
        ["investor_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investor_id", sa.UUID(), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("signed_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("terms", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("converted_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["investor_id"], ["investors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_currency"), "subscriptions", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_instrument"),
        "subscriptions",
        ["instrument"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_investor_id"),
        "subscriptions",
        ["investor_id"],
        unique=False,
    )
    op.create_table(
        "capital_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=35), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("called_on", sa.Date(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=False),
        sa.Column("notified_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capital_calls_due_on"), "capital_calls", ["due_on"], unique=False
    )
    op.create_index(
        op.f("ix_capital_calls_subscription_id"),
        "capital_calls",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "uq_capital_call_reference", "capital_calls", ["reference"], unique=True
    )
    op.create_table(
        "distributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("bank_movement_id", sa.UUID(), nullable=True),
        sa.Column("capital_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("income_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("decided_on", sa.Date(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column(
            "withholding_amount", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_movement_id"], ["bank_movements.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_distributions_bank_movement_id"),
        "distributions",
        ["bank_movement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_distributions_currency"), "distributions", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_distributions_paid_on"), "distributions", ["paid_on"], unique=False
    )
    op.create_index(
        op.f("ix_distributions_subscription_id"),
        "distributions",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "subscription_conversions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("from_subscription_id", sa.UUID(), nullable=False),
        sa.Column("to_subscription_id", sa.UUID(), nullable=False),
        sa.Column("converted_on", sa.Date(), nullable=False),
        sa.Column(
            "principal_converted", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "interest_converted", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "interest_paid_in_cash", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "conversion_terms", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("decided_by", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["to_subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_conversions_from_subscription_id"),
        "subscription_conversions",
        ["from_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_conversions_to_subscription_id"),
        "subscription_conversions",
        ["to_subscription_id"],
        unique=False,
    )
    op.create_table(
        "subscription_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investor_id", sa.UUID(), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("requested_on", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("decided_by", sa.String(length=150), nullable=True),
        sa.Column("decided_on", sa.Date(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("information_document_version", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["investor_id"], ["investors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_requests_investor_id"),
        "subscription_requests",
        ["investor_id"],
        unique=False,
    )
    op.create_table(
        "contributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bank_movement_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("capital_call_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "third_party_payer", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("third_party_reason", sa.Text(), nullable=True),
        sa.Column("attributed_by", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_movement_id"], ["bank_movements.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["capital_call_id"], ["capital_calls.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contributions_bank_movement_id"),
        "contributions",
        ["bank_movement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_capital_call_id"),
        "contributions",
        ["capital_call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contributions_currency"), "contributions", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_contributions_subscription_id"),
        "contributions",
        ["subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contributions_subscription_id"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_currency"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_capital_call_id"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_bank_movement_id"), table_name="contributions")
    op.drop_table("contributions")
    op.drop_index(
        op.f("ix_subscription_requests_investor_id"), table_name="subscription_requests"
    )
    op.drop_table("subscription_requests")
    op.drop_index(
        op.f("ix_subscription_conversions_to_subscription_id"),
        table_name="subscription_conversions",
    )
    op.drop_index(
        op.f("ix_subscription_conversions_from_subscription_id"),
        table_name="subscription_conversions",
    )
    op.drop_table("subscription_conversions")
    op.drop_index(op.f("ix_distributions_subscription_id"), table_name="distributions")
    op.drop_index(op.f("ix_distributions_paid_on"), table_name="distributions")
    op.drop_index(op.f("ix_distributions_currency"), table_name="distributions")
    op.drop_index(op.f("ix_distributions_bank_movement_id"), table_name="distributions")
    op.drop_table("distributions")
    op.drop_index("uq_capital_call_reference", table_name="capital_calls")
    op.drop_index(op.f("ix_capital_calls_subscription_id"), table_name="capital_calls")
    op.drop_index(op.f("ix_capital_calls_due_on"), table_name="capital_calls")
    op.drop_table("capital_calls")
    op.drop_index(op.f("ix_subscriptions_investor_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_instrument"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_currency"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_investor_documents_investor_id"), table_name="investor_documents"
    )
    op.drop_index(
        op.f("ix_investor_documents_expires_on"), table_name="investor_documents"
    )
    op.drop_table("investor_documents")
    op.drop_index(op.f("ix_investors_user_id"), table_name="investors")
    op.drop_index(op.f("ix_investors_iban_fingerprint"), table_name="investors")
    op.drop_index(op.f("ix_investors_email"), table_name="investors")
    op.drop_index(op.f("ix_investors_country_code"), table_name="investors")
    op.drop_table("investors")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_bank_movement_external",
        table_name="bank_movements",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_bank_movements_value_date"), table_name="bank_movements")
    op.drop_index(op.f("ix_bank_movements_currency"), table_name="bank_movements")
    op.drop_index(op.f("ix_bank_movements_account_iban"), table_name="bank_movements")
    op.drop_table("bank_movements")
    # ### end Alembic commands ###
