"""Projets, deploiements et retours

L'autre moitie de la tresorerie. L'argent entre des investisseurs, sort vers des projets,
revient des projets, ressort vers les investisseurs : quatre mouvements, et le modele n'en
portait que les deux qui concernent les investisseurs.

⚠️ MEME DISCIPLINE QUE COTE INVESTISSEUR : un deploiement et un retour sont des imputations
de MOUVEMENTS BANCAIRES, jamais des chiffres saisis seuls. Un projet dont la performance est
tapee a la main rapporte ce que son gestionnaire croit, et croire est precisement ce qu'un
investisseur paie pour ne pas avoir a faire.

🔴 Le retour est scinde capital / produit comme une distribution, et pour la meme raison :
recuperer sa propre mise n'est pas un gain. Un projet qui a rendu exactement ce qu'on lui a
donne n'a rien rapporte, et un montant unique permettrait de l'afficher comme performance.

Revision ID: 165a26c50227
Revises: 0001_baseline
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_projects"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='study', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('expected_end_on', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('immo_property_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_currency'), 'projects', ['currency'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('bank_movement_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deployed_on', sa.Date(), nullable=False),
    sa.Column('decided_by', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_movement_id'], ['bank_movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_bank_movement_id'), 'deployments', ['bank_movement_id'], unique=False)
    op.create_index(op.f('ix_deployments_currency'), 'deployments', ['currency'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_table('project_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('bank_movement_id', sa.UUID(), nullable=False),
    sa.Column('capital_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('income_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_movement_id'], ['bank_movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_returns_bank_movement_id'), 'project_returns', ['bank_movement_id'], unique=False)
    op.create_index(op.f('ix_project_returns_currency'), 'project_returns', ['currency'], unique=False)
    op.create_index(op.f('ix_project_returns_project_id'), 'project_returns', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_returns_project_id'), table_name='project_returns')
    op.drop_index(op.f('ix_project_returns_currency'), table_name='project_returns')
    op.drop_index(op.f('ix_project_returns_bank_movement_id'), table_name='project_returns')
    op.drop_table('project_returns')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_currency'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_bank_movement_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_projects_currency'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
