"""Project valuations: an opinion, with an author and a date.

🔴 A TABLE OF ROWS, NOT A COLUMN ON `projects`. A single mutable « current value » would
erase every earlier judgement the moment it moved, and the question an investor actually
asks when a figure changes is « what did you think in March, and what changed since ». A
column cannot answer it; a history can.

⚠️ NOTHING IS BACKFILLED, AND THE CONSEQUENCE IS DELIBERATE. Until somebody records a
valuation, the fund's net asset value stays UNKNOWN and TVPI keeps refusing to answer.
Stamping the deployed amount as a value would assert that every project is worth exactly
what was put into it — which is the one thing a valuation exists to test.

⚠️ `valued_on` IS INDEXED because every read asks for « the latest on or before this date »:
a report dated March must never pick up a June opinion, and that lookup runs once per
project on every performance screen.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_project_valuations"
down_revision: str | None = "0005_late_calls"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ⚠️ THE KEY IS GENERATED BY THE APPLICATION, like every other table here (`uuid_pk`).
    # A server default would work and would quietly create a second way of minting an id;
    # the day the two disagree is the day nobody can say which one wrote a row.
    op.create_table(
        "project_valuations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "project_id",
            sa.UUID(),
            sa.ForeignKey("projects.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("valued_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valued_by", sa.String(length=150), nullable=False),
        sa.Column("basis", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_project_valuations_project_id", "project_valuations", ["project_id"])
    op.create_index("ix_project_valuations_valued_on", "project_valuations", ["valued_on"])
    op.create_index("ix_project_valuations_currency", "project_valuations", ["currency"])


def downgrade() -> None:
    op.drop_index("ix_project_valuations_currency", table_name="project_valuations")
    op.drop_index("ix_project_valuations_valued_on", table_name="project_valuations")
    op.drop_index("ix_project_valuations_project_id", table_name="project_valuations")
    op.drop_table("project_valuations")
