"""The language a message is written in, decided per request rather than per process.

🔴 A LABEL THAT COMES FROM THE SERVER IS TRANSLATED AT THE SERVER. The rule is the sister
product's, and it holds for a reason this one will meet too: a statement PDF, an e-mail and a
CSV export have no front-end runtime to delegate to. If the screen translated as well, the
same vocabulary would live in two places, free to drift — and it would drift in the direction
nobody reads.

🔴 THE LANGUAGE IS A `ContextVar`, NOT A PARAMETER, and that is what makes this possible at
all. The refusals this product produces are built deep in pure functions — `accrual`,
`eligibility`, `performance` — which have no request, no user and no session. Threading a
locale through every signature would have meant touching every call site of every rule, and
the one that got missed would have answered in the wrong language silently.

⚠️ AND NEVER A MODULE-LEVEL DICT. The sister product paid for this: a catalogue computed at
import (`_LABELS = {k: translate(k) ...}`) freezes the language at the moment the process
starts, so every reader gets whatever the first one happened to be. Translation is a FUNCTION
called per request, always.

⚠️ THE DEFAULT IS FRENCH, and it is a choice rather than an accident: this product's operators
are French-speaking, and a missing `Accept-Language` should land on the language its refusals
were written in rather than on an English half-translation.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar

#: The languages this product actually carries. A code outside it falls back rather than
#: raising: a browser asking for Portuguese must get a readable page, not a 500.
SUPPORTED: tuple[str, ...] = ("fr", "en")
DEFAULT = "fr"

_current_lang: ContextVar[str] = ContextVar("current_lang", default=DEFAULT)


def normalise(lang: str | None) -> str:
    """A language code reduced to one this product serves, or the default."""
    code = (lang or DEFAULT).strip().lower()[:2]
    return code if code in SUPPORTED else DEFAULT


def set_current_lang(lang: str | None) -> None:
    _current_lang.set(normalise(lang))


def current_lang() -> str:
    return _current_lang.get()


@contextmanager
def use_lang(lang: str | None) -> Iterator[None]:
    """Force a language for a block, then restore whatever was there.

    🔴 THIS IS FOR TEXT ADDRESSED TO SOMEBODY ELSE. A statement generated by a scheduled job
    has no request and therefore no `Accept-Language`; it must still reach the investor in
    the language they chose, which `User.locale` records precisely so. Wrapping the
    generation in `with use_lang(user.locale):` is what makes that work — and it is why the
    column exists.
    """
    token = _current_lang.set(normalise(lang))
    try:
        yield
    finally:
        _current_lang.reset(token)


def lang_from_accept_language(header: str | None) -> str:
    """The first supported language of an `Accept-Language` header.

    ⚠️ QUALITY WEIGHTS ARE IGNORED ON PURPOSE. `en;q=0.9,fr;q=0.8` should give English, and
    the first supported entry does that in every real header. Parsing the weights properly
    is more code for a case that would change one answer in a thousand, and the failure mode
    of getting it wrong is silent.
    """
    if not header:
        return DEFAULT
    for part in header.split(","):
        code = part.split(";")[0].strip().lower()[:2]
        if code in SUPPORTED:
            return code
    return DEFAULT


def pick(fr: str, en: str) -> str:
    """The one of these two the current reader should see.

    ⚠️ BOTH SENTENCES SIT SIDE BY SIDE AT THE CALL SITE, and that is deliberate. A key into a
    catalogue somewhere else is tidier and makes the two versions drift: the day somebody
    rewords the French refusal, the English one keeps the old wording and nobody notices,
    because nobody reads the language they do not speak.
    """
    return en if current_lang() == "en" else fr


__all__ = [
    "DEFAULT",
    "SUPPORTED",
    "current_lang",
    "lang_from_accept_language",
    "normalise",
    "pick",
    "set_current_lang",
    "use_lang",
]
